apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-operator-system
namePrefix: cloudflare-operator-

resources:
  - ../crd
  - ../rbac
  - ../manager
  - ../default/metrics_service.yaml

patches:
  - target:
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENABLE_WEBHOOKS
            value: "false"
