FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /cfmock-server ./test/e2e/cfmock_server/

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /cfmock-server /cfmock-server
USER 65532:65532
ENTRYPOINT ["/cfmock-server"]
